// game constants
export const STAGE_WIDTH:number = 600;
export const STAGE_HEIGHT:number = 600;
export const FRAME_RATE:number = 30;

export const ASSET_MANIFEST:Object[] = [
    {
        type:"json",
        src:"./lib/Spritesheets/Alerts.json",
        id:"Alerts",
        data:0
    },
    {
        type:"image",
        src:"./lib/Spritesheets/Alerts.png",
        id:"Alerts",
        data:0
    },
    {
        type:"json",
        src:"./lib/Spritesheets/Buttons.json",
        id:"Buttons",
        data:0
    },
    {
        type:"image",
        src:"./lib/Spritesheets/Buttons.png",
        id:"Buttons",
        data:0
    },
    {
        type:"json",
        src:"./lib/Spritesheets/SelectButtons.json",
        id:"SelectButtons",
        data:0
    },
    {
        type:"image",
        src:"./lib/Spritesheets/SelectButtons.png",
        id:"SelectButtons",
        data:0
    },
    {
        type:"json",
        src:"./lib/Spritesheets/background.json",
        id:"background",
        data:0
    },
    {
        type:"image",
        src:"./lib/Spritesheets/background-0.png",
        id:"background",
        data:0
    },
    {
        type:"json",
        src:"./lib/Spritesheets/Victory.json",
        id:"Victory",
        data:0
    },
    {
        type:"image",
        src:"./lib/Spritesheets/Victory.png",
        id:"Victory",
        data:0
    },
    {
        type:"sound",
        src:"./lib/Sounds/hitHurt.ogg",
        id:"Bagel",
        data:0
    },
    {
        type:"sound",
        src:"./lib/Sounds/jump.ogg",
        id:"Pico",
        data:0
    },
    {
        type:"sound",
        src:"./lib/Sounds/pickupCoin.ogg",
        id:"VictoryNoise",
        data:0
    },
    {
        type:"sound",
        src:"./lib/Sounds/powerUp.ogg",
        id:"Fermi",
        data:0
    }
    
    
];